# Generated by Django 3.1.4 on 2020-12-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('initial_rate', models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Начальная ставка')),
                ('finish_rate', models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Конечная ставка')),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Аукцион',
                'verbose_name_plural': 'Аукцион',
            },
        ),
    ]
