# Generated by Django 3.1.4 on 2020-12-16 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='url',
        ),
        migrations.AddField(
            model_name='auction',
            name='author',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
